### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by sloakley** [tryolabs/TLSphinx#16]
Sorry if I'm being ignorant.
Downloaded the zip, not using carthage or any pacman to install it - wanted to test how modular I can make my application.

I'm having trouble importing TLSphinx. Dragged the folder into xcode, under the same hierarchy as ViewController and AppDelegate, with Copy References etc.
Updated header and include path like the setup page says.

I just cant get it to see the folder. 
Any recommendations?

**Comment by BrunoBerisso** [comment]
Hi.

TLSphinx can be tricky to integrate. The procedure your are following doesn't match the instructions in the README here. The zip contains the source code and the instructions are meant to use with Carthage.

I will recommend use Carthage for TLSphinx because it's the simpler way of install it. Do it with the source code will need much more Xcode configuration steps. The main _issue_ is that TLSphinx has a module map file for Sphinx and Pocketshpinx C libraries plus the object and headers files for both.

Also, the Carthage is not like CocoaPods. The only thing it do is download the project and build a framework (_.framework_ bundle) that you can then integrate. It doesn't mess with your Xcode project. You can even create a folder with only a Cartfile and generate the framework there outside of your project.

Try using Carthage, at last for TLSphinx, it will be much more complicated not to use it.

Thanks for try it out!

**Comment by sloakley** [comment]
Thank you for the reply.
I've built it with Carthage successfully - so thank you for that guidance.
It was very, very easy.  
However, when attempting a test import TLSwift I get an error:
/Users/lucas/Projects/Swift/micTest9/micTest9/ViewController.swift:13:8: Module file was created for incompatible target x86_64-apple-ios8.2: /Users/lucas/Projects/Swift/micTest9/Carthage/Build/iOS/TLSphinx.framework/Modules/TLSphinx.swiftmodule/x86_64.swiftmodule

I assume it's something to do with my build settings. 

Do you have guidance on this?

**Comment by BrunoBerisso** [comment]
Glad to know you find the integration easy! :D

I believe your error is because you are dragging the framework from the wrong folder. One carthage ends make sure you get the _.framework_ bundle from your _Carthage/Build/iOS_ or _Carthage/Build/OSX_ depending your project.

Let me know if that works

**Comment by BrunoBerisso** [comment]
I will close this for inactivity.
