### ISSUE TITLE
Could not find module 'TLSphinx' for architecture 'arm64'; found: i386

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [tryolabs/TLSphinx#61]
I get an error at the import statement in my Swift file when I import TLSphinx that says:

> Could not find module 'TLSphinx' for architecture 'arm64'; found: i386

**Comment by BrunoBerisso** [comment]
Hi @Shinehah-Gnolaum Sorry for the delay.

The [installation docs](https://github.com/tryolabs/TLSphinx#installation) describe two methods, which one did you use?

**Comment by Shinehah-Gnolaum** [comment]
I actually built the TLShinx project and right-click on TLSphinx.framework in the Products folder in the project and chose Show in Finder. I then copied and pasted the TLShpinx.framework file in the project folder of my project and went to the target and under General, added the framework as an embedded binary.

It was also never clear to me why I needed to follow the instructions on the README.md files of pocketsphinx-ios-demo, the pocketsphinx, and the sphinxbase repositories. It doesn't look like TLSphinx needed me to do any of that.

**Comment by BrunoBerisso** [comment]
TLSphinx is just a Swift wrapper around [CMUSphinx](https://cmusphinx.github.io/) which is a C library.

If you checked the code you would notice things like `import Sphinx.Base`, these are references to a  clang module [declared here](https://github.com/tryolabs/TLSphinx/blob/master/Sphinx/include/module.modulemap) used by TLSphinx. That's why the installation instructions ask you to add all those search paths. I didn't check the installation process with XCode 11 so this might be simpler now.

Would you mind attach here a complete log of the error? Which version of Xcode are you using?

**Comment by Shinehah-Gnolaum** [comment]
I just tried using the second method. I dragged the xcodeproj file from finder to my project. I compiled the TLSphinx project. I get this error where I have my import TLSphinx statement.

>No such module 'TLSphinx'

In following your instructions, I put the Sphinx/include path in the Header Search Paths, but not in the System Header Search Paths or the User Header Search Paths. Also the Use Header Maps is set to Yes.

**Comment by Shinehah-Gnolaum** [comment]
I suspect I need to set the Swift Compiler - Search Paths setting in Build Settings like I did in the installation using Carthage. In any case, I was able to successfully use the installation method using Carthage. I will close this.
